services:
  rabbit: 
    image: rabbitmq:management
    container_name: rabbit
    
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
      - RABBITMQ_DEFAULT_VHOST=/

    ports:
      - "5672:5672"  # AMQP протокол
      - "15672:15672" # Веб-интерфейс

